datasets:
  renewable:
    column_mapping:
      categorical_features:
        - '0'
        - '2'
        - '3'
        - '4'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
      - regression_performance
    reference_file: ./datasets/test.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
